spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
    
  application:
     name: cab-driver-service
  
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
server:
   port: 4044
      
  