spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
  
  
    
    
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      
      
server.port: 8091